# Generated by Django 4.2.1 on 2023-06-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
